apiVersion: v1
kind: LimitRange
metadata: {name: default-limits}
spec:
  limits:
  - default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
    type: Container
