apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      {{- if .Values.prometheus.scrape }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
      {{- end }}
    spec:
      imagePullSecrets:
        - name: reg-cred
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: "{{ .Values.postgres.repository }}:{{ .Values.postgres.tag }}"
          env:
            - name: POSTGRES_DB
              value: "events"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          ports:
            - name: pg
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          {{- with .Values.postgres.resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}

        - name: exporter
          image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:$(POSTGRES_PASSWORD)@localhost:5432/events?sslmode=disable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9187
